config/routes.rb
Cowview::Application.routes.draw do

	resources :kine

	resources :genes do
		collection do
			get 'add_gene'
			get 'remove_gene'
		end
	end

	root :to => "kine#index"

end

app/models/cow.rb
#encoding: utf-8
class Cow < ActiveRecord::Base
  attr_accessible :name, :code, :father_id, :mother_id, :birth, :gender

	has_many :genes, :dependent => :destroy

	belongs_to :father, :class_name => "Cow",
		:foreign_key => "father_id"

	belongs_to :mother, :class_name => "Cow",
		:foreign_key => "mother_id"

	has_many :children_of_father, :class_name => "Cow", :foreign_key => "father_id"
	has_many :children_of_mother, :class_name => "Cow", :foreign_key => "mother_id"

	validates :name, :presence => {:message => "이름을 입력해야합니다."}
	validates :code, :presence => {:message => "개체번호를 입력해야합니다."}, :uniqueness => {:message => "중복된 개체번호입니다."}

	def children
		return self.children_of_father + self.children_of_mother
	end

	def birth_str
		return birth.nil? ? "" : self.birth.to_time.strftime("%b, %d, %Y")
	end

	def gender_str
		if gender == 0 then
			return "male"
		else
			return "female"
		end
	end
end

app/models/gene.rb
#encoding: utf-8
class Gene < ActiveRecord::Base
  attr_accessible :cow_id, :f_gene, :m_gene, :name

	belongs_to :cow

	validates :f_gene, :presence => {:message => "유전자번호를 입력해야합니다."}
	validates :m_gene, :presence => {:message => "유전자번호를 입력해야합니다."}
	validates :name, :presence => {:message => "유전자 이름을 입력해야합니다."}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/genes_controller.rb
class GenesController < ApplicationController
	def add_gene
		render "add_gene"
	end

	def remove_gene
		@g_id = params[:id]
	end
end

app/controllers/kine_controller.rb
#encoding: utf-8
class KineController < ApplicationController

	def index
		@kine = Cow.all
	end

	def show
		@cow = Cow.find(params[:id])

		@genes = @cow.genes

		@mother = @cow.mother
		@father = @cow.father
	end

	def new
		@cow = Cow.new

		@mothers_m = Cow.select(["id", "gender", "name", "code"]).where(:gender => 1)
		@fathers_m = Cow.select(["id", "gender", "name", "code"]).where(:gender => 0)

	end

	def create
		begin 

			@genes = []

			@cow = Cow.new(params[:cow])

			@cow.birth = Time.new(params[:b_year], params[:b_month], params[:b_day]).to_date if params[:b_year].length > 0


			@father = Cow.where(:code => params[:father]).first unless params[:father] == ""
			@mother = Cow.where(:code => params[:mother]).first unless params[:mother] == ""

			if params[:father] != "" and @father.nil? then
				raise "부 개체의 개체번호가 잘못되었습니다."
			end

			if params[:mother] != "" and @mother.nil? then
				raise "모 개체의 개체번호가 잘못되었습니다."
			end

			@cow.father = @father unless params[:father] == ""
			@cow.mother = @mother unless params[:mother] == ""


			params[:gene].each do |g|
				if g["name"] != "" 
					gene = Gene.create!(g)
					@cow.genes << gene
					@genes << gene
				end
			end 

			@cow.save!

			render "create", :locals => {:success => true}

		rescue Exception => e

			@genes.each do |g|
				g.destroy
			end
			render "create", :locals => {:success => false, :error => @cow.errors.full_messages, :error2 => e.message}
		end
	end

	def destroy
		@cow = Cow.find(params[:id])

		@cow.destroy

		redirect_to kine_path
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/genes_helper.rb
module GenesHelper
end

app/helpers/kine_helper.rb
module KineHelper
end

app/views/genes/_add_gene_form.html.erb
<%= hidden_field_tag "genes[][id]", @gene.id, :class => "gene_form #{@gene.id}" %>

app/views/genes/_add_gene_item.html.erb
<li class="gene-item <%= @gene.id %>">
<span><%= @gene.name %></span><%= link_to "삭제", remove_gene_genes_path(:id => @gene.id), :remote => true %>
</li>

app/views/genes/_gene_form.html.erb
<tr>
	<th>
		유전자마커이름
	</th>
	<td>
		<%= text_field_tag "gene[][name]", name, :disabled => disabled %>
		<% if disabled %>
			<%= hidden_field_tag "gene[][name]", name %>
	<% end %>
	</td>
	<th>
		유전자정보
	</th>
	<td>
		<%= text_field_tag "gene[][f_gene]", "", :maxlength => 3 %> / <%= text_field_tag "gene[][m_gene]", "", :maxlength => 3 %> 
	</td>
</tr>

app/views/genes/add_gene.js.erb
var $geneItem = $('<%= j(render :partial => "gene_form", :locals => {:name => "", :disabled => false}) %>');
$('.new-gene-table').append($geneItem);

app/views/genes/remove_gene.js.erb
$('#gene-list .gene-item.<%= "#{@g_id}" %>').remove();
$('#gene-form-list .gene_form.<%= "#{@g_id}" %>').remove();

app/views/kine/_cow_row.html.erb
<tr class="cow-item">
	<td>
		<%= link_to c.name, cow_path(c), :class => "buttonize" %>
	</td>
	<td>
		<%= c.code %>
	</td>
	<td>
		<%= c.gender_str %>
	</td>
	<td>
		<%= c.birth_str %>
	</td>
	<td>
		<%= link_to "삭제", cow_path(c), :method => "delete", :class => "cow-delete-button buttonize" %>
	</td>
</tr>

app/views/kine/_new.html.erb
<div id="new-cow-form">
	<%= form_for @cow, :remote => true do |f| %>
		<table id="new-cow-table">
		<tr>
			<th>I.D. (SNU)</th>
			<td><%= f.text_field :name %></td>
		</tr>
		<tr>
			<th>성별</th>
			<td><%= f.label :gender_0, "수" %><%= f.radio_button :gender, 0 %>
			<%= f.label :gender_1, "암" %><%= f.radio_button :gender, 1 %></td>
		</tr>
		<tr>
			<th>개체번호</th>
			<td><%= f.text_field :code %></td>
		</tr>
		<tr>
			<th>생년월일</th>
			<td>
				<%= text_field_tag :b_year, "", :maxlength => 4 %>. <%= text_field_tag :b_month, "", :maxlength => 2 %>. <%= text_field_tag :b_day, "", :maxlength => 2 %>
			</td>
		</tr>
		<tr>
			<th>부</th>
			<td>
				<%= text_field_tag :father %>
			</td>
		</tr>

		<tr>
			<th>모</th>
			<td>
				<%= text_field_tag :mother %>
			</td>
		</tr>
		<tr>
			<th>유전자</th>
			<td>
				<table class="new-gene-table">
					<%= render :partial => "/genes/gene_form", :locals => {:name => "BM1824", :disabled => true} %>
					<%= render :partial => "/genes/gene_form", :locals => {:name => "BM2113", :disabled => true} %>
					<%= render :partial => "/genes/gene_form", :locals => {:name => "ETH10", :disabled => true} %>
					<%= render :partial => "/genes/gene_form", :locals => {:name => "ETH225", :disabled => true} %>
					<%= render :partial => "/genes/gene_form", :locals => {:name => "HEL1", :disabled => true} %>
					<%= render :partial => "/genes/gene_form", :locals => {:name => "SPS115", :disabled => true} %>
					<%= render :partial => "/genes/gene_form", :locals => {:name => "TGLA122", :disabled => true} %>
					<%= render :partial => "/genes/gene_form", :locals => {:name => "TGLA227", :disabled => true} %>
					<%= render :partial => "/genes/gene_form", :locals => {:name => "TGLA126", :disabled => true} %>
					<%= render :partial => "/genes/gene_form", :locals => {:name => "CSSM36", :disabled => true} %>
					<%= render :partial => "/genes/gene_form", :locals => {:name => "ETH3", :disabled => true} %>
					<%= render :partial => "/genes/gene_form", :locals => {:name => "INRA023", :disabled => true} %>
					<%= render :partial => "/genes/gene_form", :locals => {:name => "", :disabled => false} %>
				</table>
			</td>
		</tr>
		<tr>
			<td colspan="2" class="ralign">
				<%= link_to "add_gene", add_gene_genes_path, :id => "add-gene-button", :class => "buttonize", :remote => true %>
			</td>
		</tr>

		<tr>
			<td colspan="2" class="calign">
				<%= f.submit "저장(Save)", :class => "buttonize", :id => "submit-cow" %>
			</td>
		</tr>
	</table>
<% end %>	
</div>

app/views/kine/create.js.erb
<% if success then %>
		alert('생성되었습니다.');
	$('#new-cow-form').dialog("close");
	$.ajax({
		url: "/kine/new",
		type: "get",
		dataType: "script",
	});

	var $cowRow = $('<%= j(render :partial => "cow_row", :locals => {:c => @cow}) %>');

	$('#kine-table').append($cowRow);

	attachEvent();
	initUI();


<% else %>
	<% unless error2.length == 0 %>
		alert("<%= error2 %>");
	<% end %>
<% end %>

app/views/kine/index.html.erb
<div id="title">
	<h1>Cattle Genome Bank in SNU</h1>
</div>
<%= link_to "새로운 개체 정보 입력", new_cow_path, :remote => true, :class => "buttonize" %>
<table id="kine-table">
	<tr>
		<th>
			I.D. (SNU)
		</th>
		<th>
			개체번호
		</th>
		<th>
			성별
		</th>
		<th>
			생년월일
		</th>
		<th>
			옵션
		</th>
	</tr>
	<% @kine.each do |c| %>
		<%= render :partial => "cow_row", :locals => {:c => c} %>
<% end %>
</table>

app/views/kine/new.js.erb
var $new = $('<%= j(render :partial => "new") %>');

$('body').append($new);

$new.dialog({
	width: 600,
	height: 800,
	close: function(){
		$('#new-cow-form').remove();
	}
});

initUI();

app/views/kine/show.html.erb
<% content_for :stylesheets do %>
	<link rel="stylesheet" href="/assets/kine.show.css" type="text/css" />
<% end %>
<%= image_tag "snu_logo.jpg", :alt => "cow", :id => "logo" %>
<div id="head-padding"></div>
<h1>Cattle Genome Bank in SNU</h1>
<h4>서울시 관악구 관악로 1 서울대학교 수의과대학</h4>

<h2>Genotype Certificate</h2>
<h4>Case No <!-- <span class="bold">DC193101</span> --></h4>

<table id="cow-table">
	<tr>
		<td class="size2 head lalign">NAME</td>
		<td class="size4 bold c1 lalign"><%= @cow.name %></th>
		<td class="size4 bold c2 calign"><%= @cow.code %></th>
	</tr>
	<tr>
		<td class="size2 head lalign">DOB</td>
		<td class="size3 c1 lalign"><%= @cow.birth_str %></td>
		<td class="size3 c2 calign"><!-- PUREBRED --></td>
	</tr>
	<tr>
		<td id="gene-box" colspan="3">
			<ul id="gene-list">
				<% @genes.each do |g| %>
					<li class="gene-item">
				<table class="gene-table">
					<tr>
						<td class="size2 bold calign"><%= g.name %></td>
					</tr>
					<tr>
						<td class="size1 calign"><%= "#{g.f_gene}/#{g.m_gene}" %></td>
					</tr>
				</table>
				</li>
			<% end %>
			</ul>
		</td>
	</tr>
	<tr>
		<td id="sire-dam" colspan="3" class="lalign">
			<!-- span class="size4">Sire and dam qualify</span> -->
		</td>
	</tr>
	<tr id="sire">
		<td class="size2 lalign">
			Sire
		</td>
		<th class="size4 bold lalign">
			<%= @mother.name unless @mother.nil? %>
		</td>
		<th class="size4 bold calign">
			<%= @mother.code unless @mother.nil? %>
		</td>
	</tr>
	<tr id="dam">
		<td class="size2 lalign">
			Dam
		</td>
		<td class="size4 bold lalign">
			<%= @father.name unless @father.nil? %>
		</td>
		<td class="size4 bold calign">
			<%= @father.code unless @father.nil? %>
		</td>
	</tr>
	<tr id="sig1" class="sig">
		<td class="size2 lalign">Issue Date</td>
		<td class="size2 lalign"><!-- Jan 10 2008 --></td>
		<td class="size2 ralign">Adjusted to ISAG (1995) standard</td>
	</tr>
	<tr id="sig2" class="sig">
		<td class="size2 lalign">Test Date</td>
		<td class="size2 lalign"><!-- Oct 12 2007 --></td>
		<td class="size2 ralign">Conformément au standard SIGA (1995)</td>
	</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title>Cowview</title>
<meta name="viewport" content="width=device-width" />
<%= stylesheet_link_tag    "application", :media => "all" %>
<%= stylesheet_link_tag    "normalize" %>
<%= javascript_include_tag "application" %>
<%= csrf_meta_tags %>

<%= javascript_include_tag "jquery-ui-1.9.1.custom.min" %>
<%= javascript_include_tag "#{controller.controller_name}", "#{controller.controller_name}.#{controller.action_name}" %>
<%= stylesheet_link_tag "#{controller.controller_name}", "#{controller.controller_name}.#{controller.action_name}" %>

<%= stylesheet_link_tag "jquery-ui-1.9.1.custom.min" %>

<%= yield :stylesheets %>
<%= yield :javascripts %>

<style type="text/css">
<%= yield :inline_style %>
</style>


</head>
<body>

<div id="wrapper">
<%= yield %>
</div>

</body>
</html>